---
server:
  port: 8761

spring:
  main:
    banner-mode: off
  application:
    name: eureka-server

eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${server.port}}
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      #defaultZone: https://s10-14-ft-eurekaserver.azurewebsites.net/eureka/
      defaultZone: http://localhost:8761/eureka/
management:
  endpoints:
    web:
      exposure:
        include: "*"
...